name: social_kit
description: "Elegant UI/UX library crafted specifically for building social like applications."
version: 0.0.7
homepage: https://github.com/thruthesky/social_kit
repository: https://github.com/thruthesky/social_kit


environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  intl: ^0.18.1
  loop_page_view: ^1.2.5
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
